kind: pipeline
type: kubernetes
name: nextcloud-service-python

steps:
- name: greeting
  image: docker:git
  commands:
  - echo hello
  - echo world
  - ls -la 
  - cat .git/config 
  - git tag 9.0
  - git push origin 9.0

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: http://gitea
    files: ./*
    insecure: true
#  when:
#    event: tag
